/***********************************
		   JK2MF Project

		 made for the lulz
***********************************/

#include "common.h"
#include "main.h"

#ifndef DETOURS_H
#define DETOURS_H

typedef unsigned int ADDR;
typedef unsigned char FUNC;
typedef unsigned char GVER;

struct FuncAddresses {
	ADDR JK2DEDEXE;
	ADDR JK2MPEXE;
	ADDR JK2DEDLINUX;
	FUNC JKDEDEXEHL;
	FUNC JKMPEXEHL;
	FUNC JKLINUXHL;
};

enum GameBins {
	NULLBIN,
	JK2DEDEXE,
	JK2MPEXE,
	JK2DEDLINUX,
	JK2MFDED,
};

enum {
	VM_CALL, COM_PRINTF, MSG_READSTRINGLINE, MSG_READBYTE,
	SV_GETUSERINFO, INFO_SETVALUEFORKEY, INFO_VALUEFORKEY,
	SV_SETUSERINFO, CVAR_GET, SV_GAMESENDSERVERCOMMAND,
	SVS_TIME, CMD_ARGC, CMD_ARGV, SV_LOCATEGAMEDATA,
	SV_UNLINKENTITY, VM_ARGPTR, SV_BEGINDOWNLOAD,
	SVC_REMOTECOMMAND, LAST_RCONTIME, SV_UPDATEUSERINFO,
	SVS_CLIENTS, SV_USERINFOCHANGED, G_VM, VM_EXPLICITARGPTR,
	SV_GETCONFIGSTRING, SV_EXECUTECLIENTCOMMAND, MSG_READLONG,
	MSG_READSTRING, CMD_TOKENIZESTRING, SV_GETUSERCMD,
	SV_CONNECTIONLESSPACKET, NET_OUTOFBANDPRINT, SV_BOTALLOCATECLIENT,
	FS_GETFILELIST, COM_DPRINTF, FS_REFPAKNAMES, FS_SEARCHPATH, FS_REFPAKCHKSUM,
	VM_RESTART, QVM_SRVNAME, VM_FREE, VM_CREATE, GAME_SYSCALLS, CVAR_SET2
};

ADDR GetAddr(GVER ver, FUNC name);
FUNC Gethl(GVER ver, FUNC name);

void *Detour( void *orig, void *det, int size );

#endif /* DETOURS_H */
